// Code generated by "ecosystem_json_go_builder". DO NOT EDIT.
// source: ecosystem.json
package roughtime

import "github.com/cloudflare/roughtime/config"

var Ecosystem = []config.Server{
	{
		Name:          "Cloudflare-Roughtime-2",
		Version:       "IETF-Roughtime",
		PublicKeyType: "ed25519",
		PublicKey:     []byte{208, 96, 251, 115, 124, 143, 243, 17, 28, 225, 153, 118, 205, 235, 141, 217, 41, 75, 188, 53, 85, 161, 200, 236, 61, 34, 252, 253, 25, 127, 239, 56},
		Addresses: []config.ServerAddress{
			{
				Protocol: "udp",
				Address:  "roughtime.cloudflare.com:2003",
			},
		},
	},
	{
		Name:          "int08h-Roughtime",
		Version:       "IETF-Roughtime",
		PublicKeyType: "ed25519",
		PublicKey:     []byte{1, 110, 110, 2, 132, 210, 76, 55, 198, 228, 215, 216, 213, 180, 225, 211, 193, 148, 156, 234, 165, 69, 191, 135, 86, 22, 201, 220, 224, 201, 190, 193},
		Addresses: []config.ServerAddress{
			{
				Protocol: "udp",
				Address:  "roughtime.int08h.com:2002",
			},
		},
	},
	{
		Name:          "time.txryan.com",
		Version:       "Google-Roughtime",
		PublicKeyType: "ed25519",
		PublicKey:     []byte{136, 21, 99, 198, 15, 245, 143, 188, 181, 250, 68, 20, 76, 22, 29, 77, 166, 241, 10, 154, 94, 177, 79, 244, 236, 62, 15, 48, 50, 100, 217, 96},
		Addresses: []config.ServerAddress{
			{
				Protocol: "udp",
				Address:  "time.txryan.com:2002",
			},
		},
	},
	{
		Name:          "roughtime.se",
		Version:       "IETF-Roughtime",
		PublicKeyType: "ed25519",
		PublicKey:     []byte{75, 112, 51, 125, 146, 121, 10, 52, 157, 144, 157, 181, 100, 145, 155, 198, 167, 88, 63, 244, 168, 19, 199, 215, 41, 141, 62, 106, 39, 44, 122, 18},
		Addresses: []config.ServerAddress{
			{
				Protocol: "udp",
				Address:  "roughtime.se:2002",
			},
		},
	},
}
